- lib/processor.js
from my understanding, this can be removed now?
> enable windows persistent cache

- index.js
- lib/strategies/persistent.js
> Use the plugins `cacheKey`.

- index.js
- lib/processor.js
- lib/strategies/default.js
- lib/strategies/persistent.js
- test/test.js
takes warm boot of stress-app babel from (2108ms - 2600ms) -> 1400ms
Some more perf for warm and cold boots: https://github.com/stefanpenner/async-disk-cache/issues/4 coming soon.
> Improve boot

- package.json
since only used in tests, remove from deps
> rimraf is duped in deps and devDeps

- test/helpers/replacer.js
- test/test.js
> writes baseDir in tests using absolute rather than relative path

- package.json
Reverts stefanpenner/broccoli-persistent-filter#56
> Revert "Update fs-tree-diff to version 0.5.0 🚀"

- index.js
- lib/processor.js
- lib/strategies/persistent.js
- package.json
still experimenting with API/usage etc.
> Use structured logging (heimdalljs)

- index.js
We have some debug logging (avaiable via `DEBUG=broccoli-persistent-filter:*
DEBUG_LEVEL=debug`).  Add some high level info logging for the default log
level.
> Improve logging

- index.js
> Pass through name and annotation to plugin constructor.

- index.js
Provides us much more insight into the exact details of where time is being spent.
@hjdivad / @stefanpenner - Thoughts?
> Track total time spent in `processString` per build.

- README.md
> Add a note about BROCCOLI_PERSISTENT_FILTER_CACHE_ROOT in the README

- test/test.js
* generates & co for async
* => when it makes sense
* const/let when appropriate
> [CLEANUP] prefer ES6

- test/test.js
* easier to read
* more resilient
> WIP: port tests to broccoli-test-helper

- package.json
This will now use the native node implementation.
Fixes #127
cc @rwjblue
> Remove crypto package.

- package.json
> fix(package): update rsvp to version 4.7.0

- README.md
Fixing a minor typo in the code example, replacing `broccoli-filter` with `broccoli-persistent-filter`.
> Update require in code example

- README.md
- lib/strategies/persistent.js
- yarn.lock
> Allow user to clear cache by environment variable

- index.js
- test/should-persist-test.js
For issue exposed by https://github.com/ember-cli/broccoli-lint-eslint/pull/140
> [BUGFIX] FORCE_PERSISTENCE_IN_CI should not override persist option

- index.js
Add a heimdall node `_handleFile` under `applyPatches`.
Local stats are still applied to the `applyPatches` node.
> feat: Add instrumentation

- package.json
- yarn.lock
https://github.com/emberjs/ember.js/issues/17678
> Bump hash-for-dep fixing hash-for-dep issue

- index.js
There is no point in completing the function, as we know it will have no side-affects, so let's simply skip it once we know we can.
> Skip `applyPatches` if there are no patches to apply

- .jshintrc
- README.md
- index.js
- package.json
- test/helpers/simple.js
- test/test.js
- yarn.lock
Updating the module to use the Class format
> Change to class

- test/filter-test.js
Adding this test so that changes like  #188 won't break.
> verify the paths in error are as expected
